INSERT INTO users (name, age) VALUES ("John Doe", 25);
INSERT INTO users (name, age) VALUES ("John Doe", 25);
INSERT INTO users (name, age) VALUES ("John Doe", 25);
INSERT INTO users (name, age) VALUES ("John Doe", 25);
INSERT INTO users (name, age) VALUES ("John Doe", 25);
INSERT INTO users (name, age) VALUES ("John Doe", 25);
INSERT INTO users (name, age) VALUES ("John Doe", 25);
INSERT INTO users (name, age) VALUES ("John Doe", 25);
INSERT INTO users (name, age) VALUES ("John Doe", 25);
INSERT INTO users (name, age) VALUES ("John Doe", 25);
INSERT INTO users (name, age) VALUES ("John Doe", 25);
INSERT INTO users (name, age) VALUES ("John Doe", 25);
INSERT INTO users (name, age) VALUES ("John Doe", 25);
INSERT INTO users (name, age) VALUES ("John Doe", 25);
INSERT INTO users (name, age) VALUES ("John Doe", 25);
INSERT INTO users (name, age) VALUES ("John Doe", 25);
INSERT INTO users (name, age) VALUES ("John Doe", 25);
INSERT INTO users (name, age) VALUES ("John Doe", 25);
INSERT INTO users (name, age) VALUES ("John Doe", 25);
INSERT INTO users (name, age) VALUES ("John Doe", 25);


INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Boat", "Fun", "50000", 12020, 62020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Boat", "Fun", "50000", 12020, 62020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Boat", "Fun", "50000", 12020, 62020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Boat", "Fun", "50000", 12020, 62020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Boat", "Fun", "50000", 12020, 62020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Boat", "Fun", "50000", 12020, 62020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Boat", "Fun", "50000", 12020, 62020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Boat", "Fun", "50000", 12020, 62020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Boat", "Fun", "50000", 12020, 62020);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("New Boat", "Fun", "50000", 12020, 62020);

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
